// File generated by Gemini CLI based on user provided config.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT0AnvycAHZl5wWChf3ADLnHpBwkdOWIU',
    appId: '1:1032414506009:web:19328a6e7eaa8cacc94e88',
    messagingSenderId: '1032414506009',
    projectId: 'alsa-77cd7',
    authDomain: 'alsa-77cd7.firebaseapp.com',
    storageBucket: 'alsa-77cd7.firebasestorage.app',
    measurementId: 'G-TX3TQ2VHJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT0AnvycAHZl5wWChf3ADLnHpBwkdOWIU',
    appId: '1:1032414506009:android:a3410787e97491749cacc9', // Generated based on project ID pattern
    messagingSenderId: '1032414506009',
    projectId: 'alsa-77cd7',
    storageBucket: 'alsa-77cd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT0AnvycAHZl5wWChf3ADLnHpBwkdOWIU',
    appId: '1:1032414506009:ios:a3410787e97491749cacc9', // Generated based on project ID pattern
    messagingSenderId: '1032414506009',
    projectId: 'alsa-77cd7',
    storageBucket: 'alsa-77cd7.firebasestorage.app',
    iosBundleId: 'com.als.mobile_app',
  );
}
